version: 2
jobs:
  # bulding the docker images
  build:
    environment:
      PRODUCER_NAME: dalecosta/service-producer-ts
      CONSUMER_NAME: dalecosta/service-consumer-ts
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image producer
          working_directory: ./service-producer-ts/
          command: docker build -t $PRODUCER_NAME:0.3 . && docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD" && docker push docker.io/dalecosta/service-producer-ts:0.3
      - run:
          name: Build Docker image consumer
          working_directory: ./service-consumer-ts/
          command: docker build -t $CONSUMER_NAME:0.3 . && docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD" && docker push docker.io/dalecosta/service-consumer-ts:0.3

  # push image to docker hub
  publish-latest:
    environment:
      IMAGE_NAME: building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image producer to Docker Hub
          working_directory: ./service-producer-ts/
          command: echo pipeline implemented
      - run:
          name: Publish Docker Image consumer to Docker Hub
          working_directory: ./service-consumer-ts/
          command: echo pipeline implemented

# Every time we push to main.... Build docker image and 
# then publish it to the docker hub.
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main 
